INTRADAY_LOOKBACK = 60
TREND_LOOKBACK = 100

ATR_STOP_MULT = 1.5
MIN_RISK_REWARD = 2.5

# Technical pre-filter — RSI zone (4h)
RSI_BULL_MIN = 40
RSI_BULL_MAX = 70
RSI_BEAR_MIN = 30
RSI_BEAR_MAX = 60

# Macro context cache
MACRO_CACHE_TTL_HOURS = 24
LIVE_CACHE_TTL_MINUTES = 15
